import type { RegionConfig } from "./region-types";
import { englishStakeCopy } from "./stake-copy.ts";

export type { HomeSectionId, ModuleState, RegionConfig, SocialProvider } from "./region-types";

const englishManagerCopy = {
  managerSignInTitle: "Manager sign in",
  managerSignInIntroduction: "Use your administrator email and password.",
  managerEmailLabel: "Administrator email",
  managerPasswordLabel: "Password",
  managerInvalidCredentials: "The email or password is incorrect.",
  managerMissingConfiguration: "Manager login is not configured.",
  managerSignInAction: "Sign in",
  managerSignOutAction: "Sign out",
  managerBackLink: "← Back to public site",
} as const;

export const regions: Record<string, RegionConfig> = {
  china: {
    slug: "china",
    region: "China",
    siteName: "Shanghai Crypto",
    intendedDomain: "digitialhubshanghai",
    languages: { primary: "English", secondary: ["Chinese"] },
    theme: {
      primary: "#2f54d7",
      primaryText: "#ffffff",
      secondary: "#e7ad75",
      secondaryText: "#171719",
      accent: "#da5145",
      accentText: "#111111",
      background: "#f4eee7",
      text: "#171719",
      muted: "#5f5a58",
      surface: "#fffaf5",
      surfaceText: "#171719",
      surfaceMuted: "#716b69",
      dark: "#071b19",
      darkText: "#ffffff",
      darkMuted: "#c7d0cd",
    },
    identity: {
      eyebrow: "CONFLUX COMMUNITY / CHINA",
      localMark: "上海",
      symbol: "skyline",
      coordinateLeft: "31.2304° N",
      coordinateRight: "121.4737° E",
    },
    hero: {
      headline: "欢迎你",
      introduction: "Community-led Conflux hub for curious minds, committed builders and crypto-natives in Shanghai—and worldwide.",
      strip: ["BUILD LOCALLY", "连接世界", "GROW TOGETHER"],
    },
    journal: {
      name: "Journal",
      heading: "Ideas moving through the city.",
      pageHeading: "City signals.",
      introduction: "Notes from builders, community leaders and curious minds shaping the Conflux ecosystem across China.",
      emptyMessage: "The first Shanghai Crypto story is being prepared.",
      stories: [
        { slug: "shanghai-digital-finance", tag: "ECOSYSTEM", date: "18 AUG 2026", title: "Why Shanghai still sets the pace for digital finance", deck: "Builders, researchers and communities are shaping an open future from the banks of the Huangpu.", author: "Shanghai Crypto", body: "## A city built for exchange\n\nShanghai has always connected **ideas, markets and people**. Today that instinct is visible in the teams building open financial infrastructure.\n\n### What we are watching\n\n- Better payment experiences\n- Developer tools that reduce friction\n- Community knowledge that travels across borders\n\nLearn more in the [Conflux developer documentation](https://doc.confluxnetwork.org/)." },
        { slug: "meet-conflux-builders", tag: "BUILDERS", date: "12 AUG 2026", title: "Meet the teams building on Conflux", deck: "A field guide to local projects making Web3 useful, fast and distinctly their own.", author: "Shanghai Crypto", body: "## Built in public\n\nThe strongest ecosystems grow when builders can share what works, explain what failed and invite new contributors.\n\n**Shanghai Crypto** will use this Journal to make that knowledge easy to find and share." },
        { slug: "from-shanghai-to-the-world", tag: "COMMUNITY", date: "04 AUG 2026", title: "From 上海 to the world", deck: "How bilingual communities turn local knowledge into global momentum.", author: "Shanghai Crypto", body: "## Translation is infrastructure\n\nBilingual communities do more than translate words. They translate context, trust and opportunity across borders.\n\n> Local knowledge becomes more valuable when it can travel." },
      ],
    },
    stake: {
      name: "Stake CFX",
      eyebrow: "CONFLUX POS / 上海",
      headline: "Stake CFX.",
      homeHeading: "Stake into what’s next.",
      introduction: "Put your CFX to work through a clear, secure staking flow.",
      copy: englishStakeCopy,
    },
    socials: {
      instagram: { label: "Instagram", profileUrl: "https://www.instagram.com/confluxnetwork/", handle: "@confluxnetwork" },
      x: { label: "X", profileUrl: "https://x.com/Conflux_Network", handle: "@Conflux_Network" },
      youtube: { label: "YouTube", profileUrl: "https://www.youtube.com/@confluxnetwork", handle: "@confluxnetwork" },
    },
    contributors: [{ name: "Pana", role: "Conflux Core Dev", cardBio: "Superman", fullProfile: "Superman", initials: "P", visible: true }],
    modules: { journal: "use-now", stake: "use-now", contributors: "use-now", instagram: "setup-later", twitter: "setup-later", youtube: "setup-later", events: "not-needed", newsletter: "not-needed", communityLinks: "setup-later" },
    presentation: {
      bodyFont: "Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif",
      displayFont: "Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif",
      radius: "2px",
      hero: { layout: "split", visual: "skyline", visualLabel: "上海" },
      home: { sectionOrder: ["journal", "stake", "contributors", "social"], journalVariant: "rows", stakeVariant: "orbit", contributorsVariant: "portrait", socialVariant: "cards" },
      pages: { journal: "editorial-list", stake: "dark-panel" },
      copy: {
        journalEyebrow: "THE JOURNAL",
        journalLink: "All stories",
        stakeLink: "Explore staking",
        contributorsEyebrow: "PEOPLE / 人物",
        contributorsHeading: "Meet the community.",
        contributorsIntroduction: "The contributors bringing knowledge, energy and open-source craft to Shanghai Crypto.",
        socialEyebrow: "CONNECTED CHANNELS",
        socialHeading: "Follow the signal.",
        closingLine: "上海 · CHINA · CONFLUX",
        ...englishManagerCopy,
      },
    },
  },
  africa: {
    slug: "africa",
    region: "Africa",
    siteName: "Kudi Hub",
    intendedDomain: "kudihub",
    languages: { primary: "English", secondary: [] },
    theme: {
      primary: "#1f5eff",
      primaryText: "#ffffff",
      secondary: "#b9ff66",
      secondaryText: "#131916",
      accent: "#ff6b52",
      accentText: "#131916",
      background: "#071b19",
      text: "#ffffff",
      muted: "#c7d0cd",
      surface: "#f2f0e9",
      surfaceText: "#131916",
      surfaceMuted: "#4f5955",
      dark: "#071b19",
      darkText: "#ffffff",
      darkMuted: "#c7d0cd",
    },
    identity: {
      eyebrow: "CONFLUX COMMUNITY / AFRICA",
      localMark: "AF",
      symbol: "monogram",
      coordinateLeft: "6.5244° N",
      coordinateRight: "3.3792° E",
    },
    hero: {
      headline: "Built here. Open everywhere.",
      introduction: "A regional home for African builders, communities and the Conflux ecosystem.",
      strip: ["BUILD", "CONNECT", "GROW"],
    },
    journal: {
      name: "Stories",
      heading: "Money, markets and builders across Africa.",
      pageHeading: "Stories without borders.",
      introduction: "Local reporting and community knowledge from across the continent.",
      emptyMessage: "No regional feed is connected yet. Published stories will appear here automatically.",
      stories: [],
    },
    stake: {
      name: "Stake CFX",
      eyebrow: "CONFLUX POS / AF",
      headline: "Stake CFX.",
      homeHeading: "Secure participation. Shared momentum.",
      introduction: "One secure staking experience shared across every regional site.",
      copy: englishStakeCopy,
    },
    socials: {
      instagram: { label: "Instagram", profileUrl: "", handle: "" },
      x: { label: "X", profileUrl: "", handle: "" },
      youtube: { label: "YouTube", profileUrl: "", handle: "" },
    },
    contributors: [],
    modules: { journal: "use-now", stake: "use-now", contributors: "setup-later", instagram: "setup-later", twitter: "setup-later", youtube: "setup-later", events: "setup-later", newsletter: "setup-later", communityLinks: "setup-later" },
    presentation: {
      bodyFont: "Inter, Arial, sans-serif",
      displayFont: "Arial Black, Inter, sans-serif",
      radius: "0px",
      hero: { layout: "stacked", visual: "monogram-grid", visualLabel: "KUDI / AF" },
      home: { sectionOrder: ["stake", "journal", "social", "contributors"], journalVariant: "cards", stakeVariant: "statement", contributorsVariant: "compact", socialVariant: "ticker" },
      pages: { journal: "card-grid", stake: "dark-panel" },
      copy: {
        journalEyebrow: "AF / STORIES",
        journalLink: "Read all stories",
        stakeLink: "Start with staking",
        contributorsEyebrow: "PEOPLE / BUILDERS",
        contributorsHeading: "Built by the community.",
        contributorsIntroduction: "Profiles from the people moving Africa’s Conflux communities forward.",
        socialEyebrow: "COMMUNITY CHANNELS",
        socialHeading: "Across the network.",
        closingLine: "AFRICA · BUILD · CONNECT · GROW",
        ...englishManagerCopy,
      },
    },
  },
};

export function getActiveRegion(): RegionConfig {
  const slug = process.env.NEXT_PUBLIC_REGION_SLUG || "china";
  return regions[slug] || regions.china;
}

export const region = getActiveRegion();
