export const POS_POOL_ABI = [
  "event ClaimInterest(address indexed user, uint256 amount)",
  "event DecreasePoSStake(address indexed user, uint256 votePower)",
  "event IncreasePoSStake(address indexed user, uint256 votePower)",
  "event WithdrawStake(address indexed user, uint256 votePower)",
  "function _poolLockPeriod() view returns (uint256)",
  "function _poolUnlockPeriod() view returns (uint256)",
  "function birdgeAddrSetted() view returns (bool)",
  "function claimAllInterest()",
  "function decreaseStake(uint64 votePower)",
  "function increaseStake(uint64 votePower) payable",
  "function poolAPY() view returns (uint256)",
  "function poolName() view returns (string)",
  "function poolSummary() view returns (tuple(uint256 available, uint256 interest, uint256 totalInterest))",
  "function stakerNumber() view returns (uint256)",
  "function userInQueue(address account) view returns (tuple(uint256 votePower, uint256 endBlock)[])",
  "function userInQueue(address account, uint64 offset, uint64 limit) view returns (tuple(uint256 votePower, uint256 endBlock)[])",
  "function userInterest(address account) view returns (uint256)",
  "function userOutQueue(address account) view returns (tuple(uint256 votePower, uint256 endBlock)[])",
  "function userOutQueue(address account, uint64 offset, uint64 limit) view returns (tuple(uint256 votePower, uint256 endBlock)[])",
  "function userSummary(address account) view returns (tuple(uint256 votes, uint256 available, uint256 locked, uint256 unlocked, uint256 claimedInterest, uint256 currentInterest))",
  "function withdrawStake(uint64 votePower)",
  "function withdrawableCfx() view returns (uint256)",
] as const;
