export type StakeLocale = "en" | "es";

const en = {
  phaseLabel: {
    idle: "",
    validating: "Validating amount and network...",
    estimating: "Estimating gas...",
    awaiting_signature: "Confirm in your wallet...",
    submitted: "Transaction submitted",
    confirming: "Waiting for onchain confirmation...",
    success: "Transaction confirmed",
    refreshing: "Refreshing onchain data...",
    validation_error: "Check the entered amount",
    rejected: "Action cancelled",
    reverted: "Transaction failed",
    rpc_error: "Network service is temporarily unavailable",
  },
  success: {
    stake: "Stake confirmed and entering the lock period",
    unstake: "Unstake confirmed and entering the unlock period",
    withdraw: "Principal withdrawn to your wallet",
    claim: "Rewards claimed to your wallet",
  },
  approx: {
    matured: "Matured",
    days: (value: bigint) => `About ${value} days (estimated)`,
    hours: (value: bigint) => `About ${value} hours (estimated)`,
  },
  queue: {
    active: (count: number) => `${count} active ${count === 1 ? "batch" : "batches"}`,
    collapse: "Collapse −",
    expand: "Expand +",
    empty: "No queue entries",
    targetBlock: "Target block #",
    locking: "Locking",
    unlocking: "Unlocking",
    lockQueue: "Stake lock queue",
    unlockQueue: "Unstake unlock queue",
  },
  notice: {
    viewTransaction: "View transaction ↗",
    checkReceipt: "Check receipt",
    technicalDetails: "Technical details",
  },
  messages: {
    pendingFound: "Pending transaction found",
    submittedUnconfirmed: "Transaction submitted, but the receipt is not confirmed yet. Continue checking.",
    txFailed: "Transaction failed",
    confirmedRefreshing: "Transaction confirmed. Refreshing onchain data...",
    replacementConfirmed: "Replacement transaction confirmed. Refreshing onchain data...",
    replacementFailed: "The original transaction was cancelled, or its replacement failed",
    checkingReceipt: "Checking the onchain receipt...",
    stillAwaiting: "The transaction is still awaiting confirmation. An unknown status keeps this action locked.",
    rpcUnknown: "The RPC returned an unknown receipt status. This action remains locked.",
    receiptLookupFailed: "Receipt lookup failed. The transaction remains pending.",
  },
  pool: {
    overview: "POOL OVERVIEW",
    live: "View live onchain pool data without connecting a wallet.",
    totalStaked: "Total staked",
    stakers: "Stakers",
    recentApy: "Recent APY",
    unavailable: "Unavailable",
    loading: "Loading...",
    apyNote: "Historical metric, not guaranteed returns",
    unavailableError: (detail: string) => `Pool unavailable: ${detail}. Transactions are disabled.`,
  },
  wallet: {
    connect: "Connect wallet",
    restoring: "Restoring wallet...",
    network: "Conflux eSpace Mainnet",
    wrongNetwork: (chainId: string) => `Wrong network · chain ${chainId}`,
    copyAddress: "Copy address",
    switchNetwork: "Switch network",
    disconnecting: "Disconnecting...",
    disconnect: "Disconnect",
    switchTitle: "Switch to Conflux eSpace Mainnet",
    switchBody: "All staking transactions are disabled on the wrong network. The required chain ID is 1030 (0x406).",
  },
  position: {
    heading: "YOUR POSITION",
    title: "Your onchain assets",
    balanceLabel: "Wallet balance: ",
    connectPrompt: "Connect your wallet to view staking, unstaking, and reward status.",
    loading: "Loading account data...",
    unavailable: "Account data unavailable",
    staked: "Currently staked",
    availableUnstake: "Available to unstake",
    pendingUnlock: "Pending unlock",
    unlockedPrincipal: "Unlocked principal",
    withdrawable: "Currently withdrawable",
    liquidityNote: "Remaining principal is waiting for pool liquidity",
    claimable: "Claimable / total rewards",
    totalPrefix: "Total ",
  },
  actions: {
    stakeStep: "01 / STAKE",
    stakeTitle: "Stake CFX",
    stakeDescription: "Minimum 1,000 CFX in whole multiples of 1,000. Once confirmed, funds enter a lock period of about 13 days.",
    stakeAmountLabel: "Stake amount",
    stakeButton: "Stake",
    unstakeStep: "02 / UNSTAKE",
    unstakeTitle: "Unstake CFX",
    unstakeDescription: "Only funds that have completed the staking lock period can be unstaked. Once confirmed, they enter an unlock period of about one day and are not immediately available.",
    unstakeAmountLabel: "Unstake amount",
    unstakeButton: "Unstake",
    unstakeExceeds: "Entered amount exceeds the amount currently available to unstake",
    max: (value: string) => `Max ${value}`,
    withdrawStep: "03 / WITHDRAW",
    withdrawTitle: "Withdraw principal",
    withdrawDescription: "Unlocked principal may still be limited by the pool's bridge liquidity.",
    thisWithdrawal: (value: string) => `This withdrawal: ${value}.`,
    withdrawButton: "Withdraw available amount",
    withdrawLiquidityNote: "Waiting for pool withdrawal liquidity",
    rewardsStep: "04 / REWARDS",
    rewardsTitle: "Claim all rewards",
    rewardsDescription: "This version only supports claiming all rewards at once.",
    claimableLabel: (value: string) => `Claimable: ${value}.`,
    rewardsButton: "Claim all rewards",
  },
  risk: {
    heading: "RISK DISCLOSURE",
    title: "Before you submit",
    p1: "You are interacting with a third-party PoS pool proxy contract. This site never holds private keys, signs transactions for you, or asks for a seed phrase.",
    p2: "Validator penalties, contract, RPC, cross-space bridge, and liquidity risks may affect returns or settlement times. The final state is determined by the eSpace receipt and current block.",
  },
  modal: {
    kicker: "WALLET CONNECTION",
    title: "Choose a wallet",
    closeLabel: "Close wallet selection",
    closeTitle: "Close",
    intro: "Select a browser wallet to continue. The wallet extension will ask you to approve the connection.",
    opening: "Opening...",
    extension: "Browser extension",
    emptyTitle: "No compatible wallets found",
    emptyBody: "Install an EIP-6963 compatible browser wallet, then refresh this page.",
  },
  page: {
    network: "Conflux eSpace Mainnet",
    contract: (address: string) => `Contract ${address}`,
    disclaimer: "APY is a historical metric, not a fixed or guaranteed return. Staking and unstaking have lock periods, and cross-space settlement or pool liquidity may delay principal withdrawals.",
    disabledTitle: "Staking is not enabled yet",
    disabledBody: "This site does not connect wallets or move funds. The development team must connect the approved wallet and audited contract integration before enabling transactions.",
    disabledButton: "Connection pending",
  },
};

export type StakeCopy = typeof en;

const es: StakeCopy = {
  phaseLabel: {
    idle: "",
    validating: "Validando monto y red...",
    estimating: "Estimando gas...",
    awaiting_signature: "Confirma en tu billetera...",
    submitted: "Transacción enviada",
    confirming: "Esperando confirmación en la cadena...",
    success: "Transacción confirmada",
    refreshing: "Actualizando datos en la cadena...",
    validation_error: "Revisa el monto ingresado",
    rejected: "Acción cancelada",
    reverted: "Transacción fallida",
    rpc_error: "El servicio de red no está disponible temporalmente",
  },
  success: {
    stake: "Stake confirmado, ingresando al período de bloqueo",
    unstake: "Unstake confirmado, ingresando al período de desbloqueo",
    withdraw: "Principal retirado a tu billetera",
    claim: "Recompensas reclamadas a tu billetera",
  },
  approx: {
    matured: "Madurado",
    days: (value: bigint) => `Aprox. ${value} días (estimado)`,
    hours: (value: bigint) => `Aprox. ${value} horas (estimado)`,
  },
  queue: {
    active: (count: number) => `${count} ${count === 1 ? "lote activo" : "lotes activos"}`,
    collapse: "Colapsar −",
    expand: "Expandir +",
    empty: "Sin entradas en la cola",
    targetBlock: "Bloque objetivo #",
    locking: "Bloqueando",
    unlocking: "Desbloqueando",
    lockQueue: "Cola de bloqueo del stake",
    unlockQueue: "Cola de desbloqueo del unstake",
  },
  notice: {
    viewTransaction: "Ver transacción ↗",
    checkReceipt: "Verificar recibo",
    technicalDetails: "Detalles técnicos",
  },
  messages: {
    pendingFound: "Transacción pendiente encontrada",
    submittedUnconfirmed: "Transacción enviada, pero el recibo aún no está confirmado. Sigue verificando.",
    txFailed: "Transacción fallida",
    confirmedRefreshing: "Transacción confirmada. Actualizando datos en la cadena...",
    replacementConfirmed: "Transacción de reemplazo confirmada. Actualizando datos en la cadena...",
    replacementFailed: "La transacción original fue cancelada o su reemplazo falló",
    checkingReceipt: "Verificando el recibo en la cadena...",
    stillAwaiting: "La transacción sigue esperando confirmación. Un estado desconocido mantiene esta acción bloqueada.",
    rpcUnknown: "El RPC devolvió un estado de recibo desconocido. Esta acción permanece bloqueada.",
    receiptLookupFailed: "La consulta del recibo falló. La transacción sigue pendiente.",
  },
  pool: {
    overview: "RESUMEN DEL POOL",
    live: "Consulta en vivo los datos del pool en la cadena, sin conectar billetera.",
    totalStaked: "Total en stake",
    stakers: "Stakers",
    recentApy: "APY reciente",
    unavailable: "No disponible",
    loading: "Cargando...",
    apyNote: "Métrica histórica, no garantiza rendimientos",
    unavailableError: (detail: string) => `Pool no disponible: ${detail}. Las transacciones están deshabilitadas.`,
  },
  wallet: {
    connect: "Conectar billetera",
    restoring: "Restaurando billetera...",
    network: "Conflux eSpace Mainnet",
    wrongNetwork: (chainId: string) => `Red incorrecta · chain ${chainId}`,
    copyAddress: "Copiar dirección",
    switchNetwork: "Cambiar de red",
    disconnecting: "Desconectando...",
    disconnect: "Desconectar",
    switchTitle: "Cambia a Conflux eSpace Mainnet",
    switchBody: "Todas las transacciones de staking están deshabilitadas en la red incorrecta. El chain ID requerido es 1030 (0x406).",
  },
  position: {
    heading: "TU POSICIÓN",
    title: "Tus activos en la cadena",
    balanceLabel: "Saldo de billetera: ",
    connectPrompt: "Conecta tu billetera para ver el estado de tu stake, unstake y recompensas.",
    loading: "Cargando datos de la cuenta...",
    unavailable: "Datos de la cuenta no disponibles",
    staked: "En stake actualmente",
    availableUnstake: "Disponible para unstake",
    pendingUnlock: "Desbloqueo pendiente",
    unlockedPrincipal: "Principal desbloqueado",
    withdrawable: "Retirable actualmente",
    liquidityNote: "El principal restante espera liquidez del pool",
    claimable: "Reclamables / recompensas totales",
    totalPrefix: "Total ",
  },
  actions: {
    stakeStep: "01 / STAKE",
    stakeTitle: "Hacer stake de CFX",
    stakeDescription: "Mínimo 1.000 CFX, en múltiplos exactos de 1.000. Una vez confirmada, la operación entra en un período de bloqueo de aproximadamente 13 días.",
    stakeAmountLabel: "Monto de stake",
    stakeButton: "Stake",
    unstakeStep: "02 / UNSTAKE",
    unstakeTitle: "Unstake de CFX",
    unstakeDescription: "Solo los fondos que completaron el período de bloqueo pueden pasar a unstake. Una vez confirmada, la operación entra en un período de desbloqueo de aproximadamente un día y no está disponible de inmediato.",
    unstakeAmountLabel: "Monto de unstake",
    unstakeButton: "Unstake",
    unstakeExceeds: "El monto ingresado supera lo disponible actualmente para unstake",
    max: (value: string) => `Máx ${value}`,
    withdrawStep: "03 / WITHDRAW",
    withdrawTitle: "Retirar principal",
    withdrawDescription: "El principal desbloqueado puede estar limitado por la liquidez del puente del pool.",
    thisWithdrawal: (value: string) => `Este retiro: ${value}.`,
    withdrawButton: "Retirar monto disponible",
    withdrawLiquidityNote: "Esperando liquidez de retiro del pool",
    rewardsStep: "04 / REWARDS",
    rewardsTitle: "Reclamar todas las recompensas",
    rewardsDescription: "Esta versión solo permite reclamar todas las recompensas a la vez.",
    claimableLabel: (value: string) => `Reclamable: ${value}.`,
    rewardsButton: "Reclamar todas las recompensas",
  },
  risk: {
    heading: "AVISO DE RIESGO",
    title: "Antes de continuar",
    p1: "Estás interactuando con un contrato proxy de un pool PoS de terceros. Este sitio nunca guarda claves privadas, firma transacciones por ti ni solicita tu frase semilla.",
    p2: "Penalizaciones de validadores y riesgos de contrato, RPC, puente cross-space y liquidez pueden afectar los rendimientos o los tiempos de liquidación. El estado final lo determinan el recibo de eSpace y el bloque actual.",
  },
  modal: {
    kicker: "CONEXIÓN DE BILLETERA",
    title: "Elige una billetera",
    closeLabel: "Cerrar selección de billetera",
    closeTitle: "Cerrar",
    intro: "Selecciona una billetera de navegador para continuar. La extensión te pedirá aprobar la conexión.",
    opening: "Abriendo...",
    extension: "Extensión de navegador",
    emptyTitle: "No se encontraron billeteras compatibles",
    emptyBody: "Instala una billetera de navegador compatible con EIP-6963 y vuelve a cargar esta página.",
  },
  page: {
    network: "Conflux eSpace Mainnet",
    contract: (address: string) => `Contrato ${address}`,
    disclaimer: "El APY es una métrica histórica, no un rendimiento fijo ni garantizado. El staking y el unstake tienen períodos de bloqueo, y la liquidación cross-space o la liquidez del pool pueden retrasar el retiro del principal.",
    disabledTitle: "El staking aún no está habilitado",
    disabledBody: "Este sitio no conecta billeteras ni mueve fondos. El equipo de desarrollo debe conectar la integración aprobada de billetera y contratos auditados antes de habilitar transacciones.",
    disabledButton: "Conexión pendiente",
  },
};

export function stakeCopy(locale: StakeLocale = "en"): StakeCopy {
  return locale === "es" ? es : en;
}

const errorMapEs: Record<string, string> = {
  "Action cancelled": "Acción cancelada",
  "Amount must be a positive whole multiple of 1,000 CFX": "El monto debe ser un múltiplo entero de 1.000 CFX",
  "Amount exceeds the contract limit": "El monto supera el límite del contrato",
  "Wallet balance cannot cover the amount and estimated gas": "El saldo de la billetera no cubre el monto y el gas estimado",
  "Pool contract security validation failed": "Falló la validación de seguridad del contrato del pool",
  "Minimum amount is 1,000 CFX": "El monto mínimo es 1.000 CFX",
  "Stake amount parameters do not match": "Los parámetros del monto de stake no coinciden",
  "Not enough principal is available to unstake, or it remains locked": "No hay suficiente principal disponible para el unstake, o sigue bloqueado",
  "Not enough unlocked principal is available": "No hay suficiente principal desbloqueado",
  "No claimable rewards are available": "No hay recompensas reclamables disponibles",
  "The pool bridge address is not configured": "La dirección del puente del pool no está configurada",
  "Pool withdrawal liquidity is currently insufficient": "La liquidez de retiro del pool es insuficiente por ahora",
  "Network service is temporarily unavailable": "El servicio de red no está disponible temporalmente",
  "Transaction failed; funds were not changed by this request": "Transacción fallida; esta solicitud no modificó los fondos",
  "The operation did not complete. Check your wallet and network, then try again": "La operación no se completó. Revisa tu billetera y tu red, e inténtalo de nuevo",
};

export function translateStakingMessage(locale: StakeLocale, message: string) {
  return locale === "es" ? (errorMapEs[message] ?? message) : message;
}
